# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-08 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.IntegerField()),
                ('campaign_name', models.CharField(max_length=200)),
                ('user_id', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Phonebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonebook_id', models.IntegerField()),
                ('phonebook_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='phonebook_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_campaigns.Phonebook'),
        ),
    ]
