# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-09 11:49
from __future__ import unicode_literals

from django.db import migrations, models

def populating_phonebook(apps,schema_editor):
    Contacts = apps.get_model('sms_campaigns', 'Contacts')
    contact_1 = Contacts(phoneebook_id=1, contact_name='Suha', contact_no=918105533307)
    contact_1.save()


class Migration(migrations.Migration):

    dependencies = [
        ('sms_campaigns', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populating_phonebook),
    ]
