# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-11 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_campaigns', '0002_auto_20180609_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.IntegerField()),
                ('contact_no', models.IntegerField()),
                ('phonebook_id', models.ManyToManyField(to='sms_campaigns.Phonebook')),
            ],
        ),
    ]
