# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-11 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_campaigns', '0003_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='phonebook_id',
        ),
        migrations.AddField(
            model_name='campaign',
            name='phonebook_id',
            field=models.ManyToManyField(to='sms_campaigns.Phonebook'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='contact_name',
            field=models.CharField(max_length=200),
        ),
    ]
